version: 0.0
os: linux
files:
  - source: /
    destination: /opt/
hooks:
  ApplicationStop:
    - location: scripts/stop_app_if_exists.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
